services:
  - type: web
    name: bingo-bot
    plan: free
    env: python
    region: singapore
    buildCommand: |
      pip install -e . && \
      pip install -r t1x2y1/requirements.txt
    startCommand: |
      PYTHONPATH=/opt/render/project/src python -m t1x2y1.run
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: OWNER_ID
        sync: false
    healthCheckPath: /healthz
    autoDeploy: true
